version: "3.9"
services:
  postgres:
    image: postgres:17
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1235
      POSTGRES_DB: ArkDB
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  nest-app:
    build:
      context: .
    container_name: my-nest-app-backend
    ports:
      - "3333:3333"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:1235@postgres:5432/ArkDB
    networks:
      - app-network

networks:
  app-network:


#Commands:

#docker compose down --volumes
#docker compose build
#docker compose up


# Migrate
#docker exec -it my-nest-app-backend npx prisma migrate dev --name init --schema=lib/infrastructure/database/prisma-orm/prisma/schema.prisma

# Seed
#docker exec -it my-nest-app-backend npx prisma db seed --schema=lib/infrastructure/database/prisma-orm/prisma/schema.prisma

